# Generated by Django 5.0.7 on 2024-08-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportFiles',
            new_name='ReportFile',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category',), 'verbose_name_plural': 'Report Categories'},
        ),
        migrations.AlterModelOptions(
            name='moderatoraction',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Moderator Actions'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='reportfile',
            options={'ordering': ('report',), 'verbose_name_plural': 'Report Files'},
        ),
        migrations.AlterModelOptions(
            name='reportstatus',
            options={'ordering': ('status',), 'verbose_name_plural': 'Report Statuses'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('subcategory',), 'verbose_name_plural': 'Report Subcategories'},
        ),
    ]
