# Generated by Django 5.0.7 on 2024-08-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_reportfiles_reportfile_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='responsible_party',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='responsible_party_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
