# Generated by Django 5.0.7 on 2024-08-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_moderatorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorapplication',
            name='first_name',
            field=models.CharField(default='John', max_length=25),
        ),
        migrations.AddField(
            model_name='moderatorapplication',
            name='last_name',
            field=models.CharField(default='Doe', max_length=25),
        ),
    ]
