# Generated by Django 5.0.7 on 2024-08-18 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_moderatorapplication_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='subcategory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator', to='core.subcategory'),
        ),
    ]
