# Generated by Django 5.0.7 on 2024-08-18 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_moderator_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator', to='core.subcategory'),
        ),
    ]
