# Generated by Django 5.0.7 on 2024-08-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_report_latitude_alter_report_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reporter',
        ),
        migrations.AddField(
            model_name='report',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
